### PR TITLE
Fixed equivalent class axiom for skeleton structure #1033

### PR DESCRIPTION
**Pull request by kallia-p**
#1033 'skeleton structure' logical definition is too strong. EFO has these axioms creating a hidden GCI:
• skeleton structure EquivalentTo part of some skeletal system
• skeleton structure SubClassOf anatomical structure

Before doing any edits in my branch I approved and merged Nico’s pull request 
rewrite_defs_no_genus branch #989 to master
This changed the axioms a follows: 
Skeleton structure SubClassOf ‘anatomical structure’ and SubclassOf (‘part of’ some ‘skeletal system’). It only comprised one child.
In this commit I edited skeleton structure as per the suggestion in issue #1033: EquivalentTo 'anatomical structure' and ('part of' some 'skeletal system'). I deleted SubClassOf 'anatomical structure' which is now inferred and I deleted SubClassOf ‘part of’ some ‘skeletal system. However, there is no information on the term skeletal structure and I am unsure as to what exactly should classify under skeletal structure i.e. bone marrow, cartilage and joint components are probably parts of the skeletal system but they are not considered anatomical structures right??

Also I think that because I edited this after merging Nico’s pull request the diff is big and I would need some input on this edit pls.

### CODE REVIEW

**Comment by matentzn** [comment]
@kallia-p before I can review, we need to do a "normalisation PR". The reason is that, when I fixed the conflictions on the equiv_defs_merged branch, I edited the text file and didn't use Protege - however, I did not realise that the Axiom order would be that affected (the reason why there is such a big diff). 

1. change branch to master (not this branch), pull
2. make new branch (e.g. `efo_norm_032021`)
3. open efo in protege, save again without any edits.
4. make pull pull request, wait for QC to pass. you should see 93 removals and 93, or max 94, editions in the diff. You can assign me as a reviewer, or trust your judgement
5. If all ok, merge into master.
6. in your laptop again, change branch to master, pull
7. change to this branch here (`issue#1033...`)
8. In the menu of Github Desktop click "Update from master" (this merges the changes from master into your new branch. If there are conflicts i will help you.
9. commit/push
10. Ping me again!

Thank you :)

**Comment by dosumis** [comment]
For this step - you might find Protege doesn't save without a trivial edit.  

> open efo in protege, save again without any edits.

As an alternative, you can use `robot convert`  to reserialise as we did yesterday.

> However, there is no information on the term skeletal structure and I am unsure as to what exactly should classify under skeletal structure i.e. bone marrow, cartilage and joint components are probably parts of the skeletal system but they are not considered anatomical structures right??

They are anatomical structures in Uberon. 
I wouldn't worry too much.   Just eyeball to check there's nothing inferred under there that is definitely not part of a skeletal system.

**Comment by matentzn** [comment]
> For this step - you might find Protege doesn't save without a trivial edit.

Oh yeah forgot - but you can do `File > Save as >`  as a workaround (annoying)!

**Comment by kallia-p** [comment]
@matentzn @dosumis 
Thanks Nico, thanks David, these are the steps I followed as per David's demonstration 
1. In Slack #efo notifications write message Locking EFO (required when making changes to the master, not required when just working on a branch). 
2. In Github Desktop change branch to master, fetch origin.
3. In terminal cd to the src/ontology/ dir and run the command ../../bin robot convert --input efo-edit.owl --ofn --output efo-edit.owl (this will re-serialise the master file).
4. In Github Desktop commit to master, push origin.
5. Open branch (issue#1033_SkeletonStructure) and update branch (Menu select Branch and click update).
6. If there are conflicts open file in Atom and inspect. (Tip: Control + F === to find and move quickly through conflicts).
7. In Atom, click ‘use me’ (pink colour) at the top of the separating line ======  to use the AnnotationAssertion in the branch or select ‘use me’ (blue colour) at the bottom of the separating line to use the AnnotationAssertion in the master. 
8. In Atom hit save and quit Atom.
9. In Github Desktop once you see there are no conflicts remaining hit commit merge.
10. Push origin (it took ~20mins to go from step 9 to 10).
10. Wait for the QC checks to complete 
11. Merge pull request

Diff (see below) is as expected - currently I am just waiting for the QC checks to run
AnnotationAssertion(rdfs:label efo:EFO_0003858 "skeleton structure"^^xsd:string)
<<<<<<< HEAD
EquivalentClasses(efo:EFO_0003858 ObjectIntersectionOf(obo:UBERON_0000061 ObjectSomeValuesFrom(obo:BFO_0000050 obo:UBERON_0001434)))
=======
SubClassOf(efo:EFO_0003858 obo:UBERON_0000061)
SubClassOf(efo:EFO_0003858 ObjectSomeValuesFrom(obo:BFO_0000050 obo:UBERON_0001434))
>>>>>>> master
This diff is essentially saying that in my branch there is the following Equivalent class assertion:
EFO_0003858 "skeleton structure" is Equivalent To UBERON_0000061 anatomical structure and is_about some UBERON_0001434 skeletal system
Whereas in the master EFO_0003858 "skeleton structure"  is SubClass of anatomical structure and is Subclass of some skeletal system.  So I used the top one in Atom.

**Review by dosumis — APPROVED** [review]

**Pull request merged**
