### PR TITLE
Add BRAC1/2 carrier status-issues #1009 #1010

### PR DESCRIPTION
**Pull request by kallia-p**
Added new terms EFO_0011021 (BRAC1 mutation carrier status) EFO_0011022 (BRAC2 mutation carrier status) and annotations. Added Subclass Of is_about some breast cancer and Subclass Of is_about some ovarian cancer.

### CODE REVIEW

**Review by zoependlington — APPROVED** [review]
Looks good to me! You can merge and delete the branch.

**Review by dosumis — APPROVED** [review]

**Comment by dosumis** [comment]
Looks good.   I think worth keeping a note that the relationship to breast cancer is a good candidate for a different relationship than is_about.  Maybe is_risk_factor_for ?  @matentzn - Any suggestion for best venue for discussing this case?  Feels closer to a Mondo issue than phenotype/traits, so maybe a Mondo call, or perhaps a general Monarch Huddle ontology call?

**Comment by matentzn** [comment]
I would make a Mondo ticket to start from! This relationship seems so ubiquitous to me.. On the other hand, anything can be a risk factor :P have to be careful what kind of range this has..

**Comment by kallia-p** [comment]
@dosumis @matentzn Mondo sounds like the best place to talk about constructing such relationships in EFO. I 've participated and gave feedback in a few Mondo calls where these types of relationships have been discussed and all editors agree that this warrants a separate meeting and input from clinicians. Relationships such as is_risk_factor_for or predisposes_to (was suggested by Chris Mungall) would be more informative than is_about. I prefer the latter as it implies that genetic mutations are at play, whereas risk factor could be any genetic or environmental factor. Nico's point is a good one and is similar to my point about biomarkers i.e. in the literature risk factors and biomarkers for 'something' are loosely used (partly because they are still under research) but some of them are established (i.e. used in the clinic to aid prognosis, diagnosis). For common complex diseases and traits we used modifying adjectives i.e. established, strong, modest risk factor to indicate this. BRAC1/2 though are widely recognised as one of the best gene examples for predisposition to breast and ovarian cancer.

**Pull request closed without merging**
