### PR TITLE
Addressess #1881 [NTR-HCA] ECCITE-seq

### PR DESCRIPTION
**Pull request by ghost**
Addressess #1881 [NTR-HCA] ECCITE-seq

### CODE REVIEW

**Review by zoependlington — COMMENTED** [review]
Everything looks good other than the ORCID annotation for the definition should probably be definition citation rather than comment. If you can change that and make a new commit to the same branch it'll update this PR.

**Comment by bvarner-ebi** [comment]
> Everything looks good other than the ORCID annotation for the definition should probably be definition citation rather than comment. If you can change that and make a new commit to the same branch it'll update this PR.

Thank you for catching that. It should be fixed now.

**Comment by bvarner-ebi** [comment]
Unsure why "^^xsd:string" was added to several lines with the last commit. Is this an issue?

**Comment by zoependlington** [comment]
No issue, sometimes it does that! Thanks for fixing 😁

**Pull request merged**
