### PR TITLE
Addresses #1666 NTR-ExSeq

### PR DESCRIPTION
**Pull request by ghost**
Addresses #1666 NTR-ExSeq

I also added axiom: `'untargeted ExSeq' 'has part' some 'FISSEQ'`

### CODE REVIEW

**Review by zoependlington — APPROVED** [review]

**Comment by bvarner-ebi** [comment]
@zoependlington, I checked https://github.com/EBISPOT/efo/blob/master/efo-base.owl and do not see these terms. Am I missing them or do you know why these were not included?

**Comment by zoependlington** [comment]
@bvarner-ebi Could you check in efo.owl rather than efo-base.owl to see if they're there? It might be that the base hasn't been updated.

**Comment by bvarner-ebi** [comment]
@zoependlington, checking https://www.ebi.ac.uk/efo/efo.owl, I see the labels for ExSeq, but not the CURIE or IRI (for example, '0700006' can't be found in the file.

Can you confirm what the EFO production file is? Is it https://github.com/EBISPOT/efo/blob/master/efo-base.owl, and if so, when does that file get updated? 

Context is: we're trying to implement these terms in CAP.

**Comment by zoependlington** [comment]
If they have been added as EFO terms they should be in the base file, but they don't appear to be. I'll need to look into this issue. For now, I would recommend using the efo.owl file until I've had a chance to look into it.

**Pull request merged**
