### PR TITLE
Added parent term 'intestinal permeability measurement' EFO:0011031 a…

### PR DESCRIPTION
**Pull request by kallia-p**
…nd child term 'fractional excretion of lactulose to mannitol ratio' EFO:0011031 for Issue #1064

Added new term ‘intestinal permeability measurement EFO:0011031 added as Subclass Of measurement’
Subclass of is_about some ‘gastrointestinal disease’
Subclass of is_about some ‘intestinal disease’

rdfs:label "intestinal permeability measurement"@en

definition "Quantification of the intestinal permeability barrier status, for example measured by the ratio of the fractional excretion of lactulose to mannitol (LacMan ratio)"

alternative_term "gut permeability measurement"

gwas_trait true

'term editor' "Annalisa Buniello"

Added new term fractional excretion of lactulose to mannitol ratio EFO:0011031

Subclass of intestinal permeability measurement

rdfs:label "fractional excretion of lactulose to mannitol ratio"@en

definition "The gold standard for functional measurements of intestinal permeability in humans is the lactulose/ mannitol test, which measures urinary excretion of the two orally administered non-metabolized sugars over a 6 h period. Analysis by high pressure liquid chromatography or liquid chromatography in combination with mass spectrometry is usually performed on urine samples."

Annotated the definition to doi/pdf/10.1111/nmo.12871
https://onlinelibrary.wiley.com/doi/pdf/10.1111/nmo.12871

alternative_term "LacMan ratio"

alternative_term "lactulose mannitol test"

database_cross_reference "PMID:31251335"

gwas_trait true

### CODE REVIEW

**Comment by kallia-p** [comment]
@buniello @zoependlington In keeping with introducing more structure to the measurement branch I propose in this pull request to add two new terms: parent term 'intestinal permeability measurement' EFO:0011032 added as Subclass Of measurement and child term 'fractional excretion of lactulose to mannitol ratio' EFO:0011031. More details are in the description of the commit. If this is not fine by Annalisa for the purposes of your annotation pls let me know and I will keep just the intestinal permeability measurement term.

**Review by zoependlington — APPROVED** [review]
Just a note that intestinal disease is a child of gastrointestinal disease, therefore having the "is about" for both is not necessary, you only require "is_ about some intestinal disease". It's not a breaking issue, but just a bit of redundancy.

**Comment by kallia-p** [comment]
Thanks Zoe, I removed it in the last commit to avoid redundancy and merged.

**Comment by kallia-p** [comment]
@buniello 
Added new term 'fractional excretion of lactulose to mannitol ratio' EFO:0011032 under parent term ‘intestinal permeability measurement' EFO:0011031.

**Pull request merged**
